#pragma once
#ifndef __GAME_OBJECT_TYPE__
#define __GAME_OBJECT_TYPE__
enum GameObjectType {
	NONE = -1,
	PLAYER,
	BULLET,
	ENEMY,
	ENEMY_BULLET,
	SHIP,
	COMET,	
	START_BUTTON,
	TUTORIAL_BUTTON,
	NEXT_LEVEL_BUTTON,
	BACK_GROUND,
	POWER_UP,
	NUM_OF_TYPES,
	MISSILE
};

#endif /* defined (__GAME_OBJECT_TYPE__)*/